spring:
  application:
    name: students
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/school_micro_sample
    username: postgres
    password: kyawe
    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8090

